export enum CODES {
  FAIL = 'FAIL',
  SUCCESS = 'SUCCESS',
  GET_SESSION_INFO_FAIL = 'GET_SESSION_INFO_FAIL',
  CREATE_OPERATION_FAIL = 'CREATE_OPERATION_FAIL',
  AUTH_FAIL_WRONG_CREDENTIAL = 'AUTH_FAIL_WRONG_CREDENTIAL'
}